# Generated by Django 2.2.24 on 2021-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='value',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
