# Generated by Django 2.2.24 on 2021-08-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210828_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
